-keep class androidx.compose.** { *; }
-keep class * extends androidx.room.RoomDatabase { *; }
-keep class * extends androidx.lifecycle.ViewModel { *; }
-keep class org.koin.** { *; }
-keep class kotlinx.coroutines.** { *; }
-keepattributes SourceFile,LineNumberTable
-keep class xyz.wingio.logra.** { *; }
